### ISSUE TITLE
Spritesmith 更新到 1.0 版本

### ISSUE THREAD

**Issue by unmric** [laoshu133/grunt-css-sprite#23]
旧版本会导致 WINDOWS 系统安装错误 (某种众所周知原因).
并且会启动编译器编译非默认引擎 `canvassmith`. 

Spritesmith 1.0 版本 使用了 `pixelsmith` 作为默认处理引擎. 支持更多图像格式, 并不依赖系统环境.

并且没有其他的疑难杂症.

**Comment by laoshu133** [comment]
感谢更新
