### ISSUE TITLE
优化合并 retinae 图像的逻辑

### ISSUE THREAD

**Issue by 17** [laoshu133/grunt-css-sprite#25]
例如这个项目的测试
 
合并图像完成后, `@media` 会带着一串 `background-position`, 在不启用 `padding` 参数时, 这串内容是和原本的无差异的. 启用 `padding` 后, 在合并 `retinae` 图像时 `padding` 的数值并没有随之增加. 这才导致 `background-position` 值的不同.

我觉得这段相同的代码是可以优化的, 这个也可以减轻这个项目的复杂性. 
至于`padding` 参数, 可以在合并 `retinae` 图像的时候对 `padding` 值进行处理 (X2).

另: `background-size` 默认是 `auto` [1], 378 行也可以稍微的优化一下. 
1. https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

**Comment by laoshu133** [comment]
`padding ` 的计算确实是疏忽了，由于项目中一般未使用 `padding` 也一直未发现问题，感谢指正，将尽快修复；
`background-size: {N}px auto`  其实是为了指定宽度，然后高度浏览器自己适配

**Comment by unmric** [comment]
因为 `background-size` 默认就是 `auto auto`,
所以设置 `background-size: {imgsize}` 和 `background-size: {imgsize} auto` 是没有差异的.

**Comment by laoshu133** [comment]
今天重新理了一遍 sprite 的流程， retina `padding` 值的计算确实有疏忽，但不对实际使用有影响，相反还可以减少图片体积，因为最后计算 `background-size` 是通过生成后的图片计算的。
另外，目前正在计划下一版发布，将支持选择器提取，不会再生成大量的 `background-image, background-size`

**Comment by unmric** [comment]
NICE! 因为不用 `padding` 的时候, 也有些无用的 `background-position` 看起来不怎么爽...

**Comment by laoshu133** [comment]
现已更新，且发布至 npm ^_^
