### ISSUE TITLE
望支持图片文件名

### ISSUE THREAD

**Issue by xuexb** [laoshu133/grunt-css-sprite#26]
有的场景下不希望所有的`sprite`图放一块的，比如`icon`标放一块，其他放一块。。。而现在是以css名的话就不能了，如果开启`newsprite`的话每次都是新的，还得手动删除旧的额。。。

**Comment by az8321550** [comment]
这个还是支持下比较好，不然太不灵活了

**Comment by xuexb** [comment]
赞

**Comment by stoneChen** [comment]
这个问题，是不是可以这么解决：在最初开发页面的时候，就按图片目录分类好，然后分开多个子任务自动合并。
比如：
把a1.png, a2.png, a3.png放在images/a目录下
把b1.png, b2.png, b3.png放在images/b目录下
然后Gruntfile.js:
````javascript
...
sprite:{
   a:{
        src:'images/a/**.*.png',
        dest:'dist/images/a.sprite.png'
   },
   b:{
        src:'images/b/**.*.png',
        dest:'dist/images/b.sprite.png'
   }
}
...
````

**Comment by az8321550** [comment]
@stoneChen 你这种方法只不过是另辟蹊径，没有根本的解决问题！

**Comment by xuexb** [comment]
我本地已扩展了一个imgName

**Comment by ar-insect** [comment]
为何在本地无法产出雪碧图，而css可以产出，配置如下：

sprite: {
      autoSprite: {
        imagepath: 'images/slice/*.png',
        spritedest: 'assets/dist/images/button.sprite.png',
        src:'static/css/*.css',
        dest:'assets/dist/css/button.sprite.css'
      }
    }

不知道有什么问题，指教。

**Comment by az8321550** [comment]
没问题，下次再搞吧

**Comment by iulo** [comment]
这个问题还没有修复吗？

**Comment by cymmint** [comment]
同问，如果改图片输出名字
