### ISSUE TITLE
如何避免不必要的背景图片？

### ISSUE THREAD

**Issue by angela-huang** [laoshu133/grunt-css-sprite#27]
如果把不需要的背景图片读出来了怎么办？比如我的一篇文章只有右上角用到背景，这样应该会把其他背景图片也一起加载进来吧？这个要如何处理？

**Comment by laoshu133** [comment]
不是很明白你意思，背景图只有当 CSS 内有引用，且满足配置条件的时候才会处理，应该不存在多余的情况

**Comment by angela-huang** [comment]
![image](https://cloud.githubusercontent.com/assets/11454043/7791035/df2735d8-02ca-11e5-829e-7b0ce4115f9c.png)
就是像这样我只要那个灰色星星作为背景，但其他地方的背景也一起读出来了

**Comment by laoshu133** [comment]
背景图会自动拼合，所以需要你保证容器大小 <= 雪碧图大小；
`grunt-css-sprite` 不适用于大容器 + `padding` 等背景，不适用于背景平铺

**Comment by angela-huang** [comment]
嗯，了解叻。谢谢咯~那在适用的情况下对图片路径有要求吗？就是之前我问的第二个问题，如果我把图片直接放在一个文件夹下就可以，但如果我在一个文件夹下再分几个文件夹就调试不出来了

**Comment by laoshu133** [comment]
可以的，检查下路径对不对，是不是最版本
